services:
  - type: web
    name: evg-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: INITIAL_ADMIN_USER
        value: admin
      - key: INITIAL_ADMIN_PASSWORD
        sync: false   # set manually in Render dashboard
